### ISSUE TITLE
Create similar app for others School or University 

### ISSUE THREAD

**Issue by azispratama92** [pawitp/muwifi-autologin#2]
My campus using web login for the WiFi.

With the address http://internet.ugm.ac.id

Its aks email and user password, since I want to automate my login, is it possible to modify your code to do so ? 

p.s I'm newbie programmer from Indonesia,  many thanks Sir :smiley:

**Comment by pawitp** [comment]
Please feel free to fork the project and modify the code for your use. I cannot do it because I do not have access to your university's network.
